site_name: My Docs

nav:
  - HOME: index.md
  - ABOUT: about.md
  - WORKS: works.md

theme:
  name: material
  palette:
    primary: blue grey

on:
  push:
    branchs:
      - main
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
