site_name: ymsk-sky.github.io

nav:
  - index.md

repo_url: https://github.com/ymsk-sky/ymsk-sky.github.io
repo_name: source

theme:
  name: material
  language: ja
  palette:
    primary: blue grey
  icon:
    repo: fontawesome/brands/github

extra:
  search:
    language: jp
